<#
    POLARIS - one-command PostgreSQL setup (Windows)

        powershell -ExecutionPolicy Bypass -File database\setup_database.ps1

    What it does
      1. asks for your PostgreSQL superuser password (never echoed, never stored)
      2. asks for a password to give the new `polaris` role
      3. creates the role and the `polaris` database
      4. writes backend\.env with the polaris password

    Your superuser password is used only for this session and is discarded.
#>

$ErrorActionPreference = 'Stop'

$root      = Split-Path -Parent $PSScriptRoot
$envFile   = Join-Path $root 'backend\.env'
$dbName    = 'polaris'
$dbUser    = 'polaris'

Write-Host ''
Write-Host '======================================================================'
Write-Host ' POLARIS - PostgreSQL setup'
Write-Host '======================================================================'

# --- locate psql -----------------------------------------------------------
$psql = (Get-Command psql -ErrorAction SilentlyContinue).Source
if (-not $psql) {
    $candidates = Get-ChildItem 'C:\Program Files\PostgreSQL\*\bin\psql.exe' -ErrorAction SilentlyContinue |
                  Sort-Object FullName -Descending
    if ($candidates) { $psql = $candidates[0].FullName }
}
if (-not $psql) {
    Write-Host ''
    Write-Host '  ERROR: psql.exe not found.' -ForegroundColor Red
    Write-Host '  Install PostgreSQL or add its bin directory to PATH.'
    exit 1
}
Write-Host "  psql: $psql"

# --- gather credentials ----------------------------------------------------
Write-Host ''
Write-Host '  Enter the password for the PostgreSQL superuser (usually "postgres").'
Write-Host '  It is used only to create the role and database, and is not saved.'
$superSecure = Read-Host '  postgres password' -AsSecureString
$superPlain  = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($superSecure))

Write-Host ''
Write-Host "  Choose a password for the new '$dbUser' application role."
$appSecure = Read-Host "  $dbUser password" -AsSecureString
$appPlain  = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($appSecure))

if ([string]::IsNullOrWhiteSpace($appPlain)) {
    Write-Host '  ERROR: the application password cannot be empty.' -ForegroundColor Red
    exit 1
}

# --- create role + database ------------------------------------------------
$env:PGPASSWORD = $superPlain
$escaped = $appPlain.Replace("'", "''")

Write-Host ''
Write-Host '  Creating role and database ...'

$sql = @"
DO `$`$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$dbUser') THEN
      CREATE ROLE $dbUser LOGIN PASSWORD '$escaped';
      RAISE NOTICE 'role $dbUser created';
   ELSE
      ALTER ROLE $dbUser LOGIN PASSWORD '$escaped';
      RAISE NOTICE 'role $dbUser already existed - password updated';
   END IF;
END
`$`$;
"@

$sql | & $psql -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -q
if ($LASTEXITCODE -ne 0) {
    Write-Host '  ERROR: could not create the role. Check the superuser password.' -ForegroundColor Red
    $env:PGPASSWORD = $null
    exit 1
}

$exists = & $psql -U postgres -h localhost -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'"
if ($exists -ne '1') {
    & $psql -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -q -c "CREATE DATABASE $dbName OWNER $dbUser ENCODING 'UTF8'"
    if ($LASTEXITCODE -ne 0) {
        Write-Host '  ERROR: could not create the database.' -ForegroundColor Red
        $env:PGPASSWORD = $null
        exit 1
    }
    Write-Host "  database '$dbName' created"
} else {
    Write-Host "  database '$dbName' already exists"
    & $psql -U postgres -h localhost -d postgres -q -c "ALTER DATABASE $dbName OWNER TO $dbUser" | Out-Null
}

& $psql -U postgres -h localhost -d $dbName -q -c "GRANT ALL ON SCHEMA public TO $dbUser" | Out-Null
$env:PGPASSWORD = $null

# --- verify the app role can actually connect ------------------------------
Write-Host '  Verifying the application login ...'
$env:PGPASSWORD = $appPlain
$check = & $psql -U $dbUser -h localhost -d $dbName -tAc 'SELECT 1'
$env:PGPASSWORD = $null
if ($check -ne '1') {
    Write-Host '  ERROR: the polaris role could not connect.' -ForegroundColor Red
    exit 1
}
Write-Host '  login OK'

# --- write backend/.env ----------------------------------------------------
$envBody = @"
# POLARIS - local backend configuration
# Generated by database\setup_database.ps1

POSTGRES_USER=$dbUser
POSTGRES_PASSWORD=$appPlain
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=$dbName

DB_ECHO=false
DEBUG=true
API_PREFIX=/api
CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173

ALLOW_NETWORK_INGEST=true
WEATHER_TIMEOUT_S=25

HISTORY_DAYS=120
FORECAST_HORIZON_H=72
RANDOM_SEED=20260921
"@

Set-Content -Path $envFile -Value $envBody -Encoding utf8
Write-Host "  wrote $envFile"

Write-Host ''
Write-Host '======================================================================'
Write-Host ' Database ready.'
Write-Host '======================================================================'
Write-Host ''
Write-Host '  Next:'
Write-Host '    cd backend'
Write-Host '    .\.venv\Scripts\python.exe -m scripts.init_db'
Write-Host '    .\.venv\Scripts\python.exe -m scripts.bootstrap'
Write-Host ''
